<a href="https://colab.research.google.com/github/varshanookarapu/Customer_Shopping_Behaviour_Analysis_Python/blob/main/customer_shopping_behaviour_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


The agenda of this project is to first understand the problem statement,then analyze customer shopping behavior in detail, clean the data, and perform exploratory data analysis (EDA) and  document the data-cleaning steps along with the logical thought process behind each step.


Link  :https://www.youtube.com/watch?v=5PrZvPeUw60

## Problem Statement
 A leading retail company wants to better understand its customers’ shopping behavior in order improve sales, customer satisfaction, and long-term loyalty. The management team has noticed changes in purchasing patterns across demographics, product categories, and sales channels (online vs. offline). They are particularly interested in uncovering which factors, such as discounts, reviews, seasons, or payment preferences, drive consumer decisions and repeat purchases.
You are tasked with analyzing the company’s consumer behavior dataset to answer the following overarching business question:


**“How can the company leverage consumer shopping data to identify trends, improve customer engagement, and optimize marketing and product strategies?”**

In [12]:
from google.colab import files  ## so bascially i do not have jupyter notebook on my computer and I am using google collab , to get the file , I had to use the import files library and upload the csv file.

In [14]:
uploaded = files.upload()

In [81]:
import pandas as pd;
import numpy as np;

In [82]:
customer_behaviour_df = pd.read_csv("customer_shopping_behavior.csv")  ## Finally I got the file in a data frame now .

###Cheklist For Data Cleaning

1.Check the shape of the data (total rows and total columns)

2.Check for the column names if they are copacetic and update the case and the format if needed

3.Check for missing values or null values in every column

4.Count the missing values or null values and determine if you need to impute the data ( by using mean,median, first up or first down approach )

5.Remove the duplicates

6.Check the data types of every column and convert them where needed

7.Check the statistical summary of every data column

8. Add in new columns if needed based on the existing columns

In [17]:
## Checking the shape of data
customer_behaviour_df.shape

(3900, 18)

In [18]:
## Checking all the info - gives more detailed summary with null counts
customer_behaviour_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [19]:
# Checking the datatypes - No data type converstion are required
customer_behaviour_df.dtypes

Customer ID                 int64
Age                         int64
Gender                     object
Item Purchased             object
Category                   object
Purchase Amount (USD)       int64
Location                   object
Size                       object
Color                      object
Season                     object
Review Rating             float64
Subscription Status        object
Shipping Type              object
Discount Applied           object
Promo Code Used            object
Previous Purchases          int64
Payment Method             object
Frequency of Purchases     object
dtype: object

In [83]:
## Checking for missing or null values in every column
customer_behaviour_df.isna().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [21]:
## Its is evident that Review column has 37 null values , I will update those with the rating "unknown"
##customer_behaviour_df["Review Rating"] = customer_behaviour_df["Review Rating"].fillna("Unknown")
##customer_behaviour_df[customer_behaviour_df["Review Rating"] == "unknown"]
## It did cross my mind to update the review rating to zero but then rating 0 means its bad so I just chose to make it unknown.

In [22]:
#At first, my intuition was to replace the missing values with "Unknown", since there are only 37 missing values out of 3,900. However, after referring to the video, I realized that imputing the missing values
# using the median is a better approach. Another good point he made was regarding why we choose mean or median for imputation in the first place. In this case, we prefer the median over the mean because the mean can
#be significantly affected by outliers, which can skew the data distribution. Therefore, using the median provides a more robust estimate. Even with the median, he did not simply calculate the median of all the ratings
# and use that value to replace every missing entry. Instead, he calculated the median rating for each category and used the corresponding category-level median to fill in the missing values.
#This is a much more logical and meaningful way to impute the data because the typical rating can vary across different categories.
#Overall, I think this is a really good approach to handling the missing values in the dataset.

In [84]:
#Based on the above observation , I will now try to find median review rating for every category.

# Another important distinction is median() reduces the data , transform("median") will keep the data set as is and then update the values

customer_behaviour_df.groupby("Category")["Review Rating"].median().reset_index(name="Median Review Rating")

      Category  Median Review Rating
0  Accessories                   3.8
1     Clothing                   3.7
2     Footwear                   3.8
3    Outerwear                   3.8

In [24]:
## Now i will replace the median review rating in all the missing values .

customer_behaviour_df["Review Rating"] = customer_behaviour_df["Review Rating"].fillna(customer_behaviour_df.groupby("Category")["Review Rating"].transform("median"))

In [25]:
## Now I will check for duplicates and drop them  - bascially i am using duplicated function with sum to check and count the duplicates and if there are any duplicates i will use drop_duplicates() to remove them. and then put it in another df and check the shape of the data .
customer_behaviour_df.duplicated().sum()
## for now there's no duplicates in the data

np.int64(0)

In [85]:
## Statistical Summary
customer_behaviour_df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [86]:
## As we have seen above the column names have spaces in them  for better readability I will now convert those column names to lower and replace spaces with underscores


customer_behaviour_df.columns = customer_behaviour_df.columns.str.lower().str.replace(" ","_")

customer_behaviour_df= customer_behaviour_df.rename(

    {
        "purchase_amount_(usd)": "purchase_amount_usd",
    }
    )

In [87]:

customer_behaviour_df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [88]:
customer_behaviour_df.groupby("frequency_of_purchases").count()["customer_id"]

frequency_of_purchases
Annually          572
Bi-Weekly         547
Every 3 Months    584
Fortnightly       542
Monthly           553
Quarterly         563
Weekly            539
Name: customer_id, dtype: int64

In [92]:
## Mapping Days to Frequency purchases

frequency_mapping = {

  "Annually" : 365,
  "Bi-Weekly" : 14,
  "Every 3 Months" : 90,
  "Fortnightly" : 14,
  "Monthly" : 30,
  "Quarterly" : 90,
  "Weekly" : 7

}

customer_behaviour_df["purchase_frequency_days"] = customer_behaviour_df["frequency_of_purchases"].map(frequency_mapping)

customer_behaviour_df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,365

In [96]:
## creating an age group column

age_group_list = ["Young_Adult","Adult","Middle Aged","Senior"]


customer_behaviour_df["age_group"] = pd.qcut(customer_behaviour_df["age"],q=4,labels=age_group_list)


customer_behaviour_df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,purchase_frequency_days,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,14,Middle Aged
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,14,Young_Adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,7,Middle Aged
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,7,Young_Adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,365,Middle Aged

In [109]:
## Removing unnecessary columns

# (customer_behaviour_df["discount_applied"] == customer_behaviour_df["promo_code_used"]).all()

# customer_behaviour_df = customer_behaviour_df.drop(columns=["promo_code_used"])
customer_behaviour_df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'purchase_frequency_days', 'age_group'],
      dtype='object')

After the above data cleaning steps, I have ensured there are no null values / duplicates in the data set and all the data types are accurate ,and will now procced to further analysis.

Based on this  " The management team has noticed changes in purchasing patterns across demographics, product categories, and sales channels (online vs. offline)"

The questions I can analyse are

1.How many male and female customers are there in the dataset

2.Out of those how many purchased online / offilne ( sales channels)

3.Who among all the customers have more previous purchases top 5 , under which season and  check the discouts , promo codes , shipping type

4.Finding seasonal purchases , like How many customers purchased  in every season

5.Customers purchase frequency analysis

6.Which item has more reviews and how many people purchased it